<?php
return [
    [
        'id' => 'spotify',
        'label' => 'Spotify',
        'logo' => '/assets/logos/dsp/spotify.svg',
        'color' => '#1DB954',
        'url_prefix' => 'https://open.spotify.com/search/',
    ],
    [
        'id' => 'apple_music',
        'label' => 'Apple Music',
        'logo' => '/assets/logos/dsp/apple-music.svg',
        'color' => '#FA2D48',
        'url_prefix' => 'https://music.apple.com/search?term=',
    ],
    [
        'id' => 'deezer',
        'label' => 'Deezer',
        'logo' => '/assets/logos/dsp/deezer.svg',
        'color' => '#EF5466',
        'url_prefix' => 'https://www.deezer.com/search/',
    ],
    [
        'id' => 'amazon_music',
        'label' => 'Amazon Music',
        'logo' => '/assets/logos/dsp/amazon-music.svg',
        'color' => '#00A4E3',
        'url_prefix' => 'https://music.amazon.com/search/',
    ],
    [
        'id' => 'youtube_music',
        'label' => 'YouTube Music',
        'logo' => '/assets/logos/dsp/youtube-music.svg',
        'color' => '#FF0033',
        'url_prefix' => 'https://music.youtube.com/search?q=',
    ],
    [
        'id' => 'tiktok',
        'label' => 'TikTok',
        'logo' => '/assets/logos/dsp/tiktok.svg',
        'color' => '#69C9D0',
        'url_prefix' => 'https://www.tiktok.com/search?q=',
    ],
    [
        'id' => 'boomplay',
        'label' => 'Boomplay',
        'logo' => '/assets/logos/dsp/boomplay.svg',
        'color' => '#00D775',
        'url_prefix' => 'https://www.boomplay.com/search/',
    ],
    [
        'id' => 'itunes',
        'label' => 'iTunes',
        'logo' => '/assets/logos/dsp/itunes.svg',
        'color' => '#FA2D48',
        'url_prefix' => 'https://itunes.apple.com/search?term=',
    ],
    [
        'id' => 'jiosaavn',
        'label' => 'JioSaavn',
        'logo' => '/assets/logos/dsp/jiosaavn.svg',
        'color' => '#00BFA5',
        'url_prefix' => 'https://www.jiosaavn.com/search/',
    ],
    [
        'id' => 'qq_music',
        'label' => 'QQ Music (Tencent)',
        'logo' => '/assets/logos/dsp/qq-music.svg',
        'color' => '#FFC700',
        'url_prefix' => 'https://y.qq.com/n/ryqq/search?w=',
    ],
    [
        'id' => 'napster',
        'label' => 'Napster',
        'logo' => '/assets/logos/dsp/napster.svg',
        'color' => '#0077C5',
        'url_prefix' => 'https://app.napster.com/search/',
    ],
    [
        'id' => 'tidal',
        'label' => 'TIDAL',
        'logo' => '/assets/logos/dsp/tidal.svg',
        'color' => '#0A0A0A',
        'url_prefix' => 'https://tidal.com/browse/search/',
    ],
];
